config/routes.rb
Kassi::Application.routes.draw do
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  match "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get '/webhooks/braintree' => 'braintree_webhooks#challenge'
  post '/webhooks/braintree' => 'braintree_webhooks#hooks'
  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook

  post '/bounces' => 'amazon_bounces#notification'

  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :admin do
    match '' => "communities#getting_started"
  end

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    get "/check_email_availability" => "marketplaces#check_email_availability"
  end

  REMOVED_LOCALES = Rails.application.config.REMOVED_LOCALES.to_a

  locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(REMOVED_LOCALES).join("|"))

  match '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  match '/' => 'homepage#index', as: :homepage_without_locale
  root :to => 'homepage#index'

  match '/500' => 'errors#server_error'
  match '/404' => 'errors#not_found', :as => :error_not_found
  match '/410' => 'errors#gone', as: :error_gone
  match '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    match '/mercury_update' => "mercury_update#update", :as => :mercury_update, :method => :put

    match "/transactions/op_status/:process_token" => "transactions#op_status", :as => :transaction_op_status

    match "/transactions/new" => "transactions#new", as: :new_transaction

    match "/listings/:listing_id/preauthorize" => "preauthorize_transactions#preauthorize", :as => :preauthorize_payment
    match "/listings/:listing_id/preauthorized" => "preauthorize_transactions#preauthorized", :as => :preauthorized_payment
    match "/listings/:listing_id/book" => "preauthorize_transactions#book", :as => :book
    match "/listings/:listing_id/booked" => "preauthorize_transactions#booked", :as => :booked
    match "/listings/:listing_id/initiate" => "preauthorize_transactions#initiate", :as => :initiate_order
    match "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    match "/listings/:listing_id/post_pay" => "post_pay_transactions#new", :as => :post_pay_listing
    match "/listings/:listing_id/create_transaction" => "post_pay_transactions#create", :as => :create_transaction, :method => :post

    match "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    match "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    match "/listings/new/:type/:category" => "listings#new", :as => :new_request_category
    match "/listings/new/:type" => "listings#new", :as => :new_request
    match "/logout" => "sessions#destroy", :as => :logout, :method => :delete
    match "/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
    match "/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
    match "/login" => "sessions#new", :as => :login
    match "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    match "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    match '/:person_id/settings/payments/braintree/new' => 'braintree_accounts#new', :as => :new_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/show' => 'braintree_accounts#show', :as => :show_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/create' => 'braintree_accounts#create', :as => :create_braintree_settings_payment
    match '/:person_id/settings/payments/braintree/add_braintree_customer' => 'braintree_accounts#add_braintree_customer', :as => :add_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/update_braintree_customer' => 'braintree_accounts#update_braintree_customer', :as => :update_braintree_settings_customer
    match '/:person_id/settings/payments/braintree/create_braintree_customer' => 'braintree_accounts#create_braintree_customer', :as => :create_braintree_settings_customer
    match '/:person_id/settings/payments/paypal_account/new' => 'paypal_accounts#new', :as => :new_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/show' => 'paypal_accounts#show', :as => :show_paypal_account_settings_payment
    match '/:person_id/settings/payments/paypal_account/create' => 'paypal_accounts#create', :as => :create_paypal_account_settings_payment
    get '/auth_stripe' =>"transactions#auth_stripe"
    post "/listing_calculation" => "listings#listing_calculation"

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
            put :verify_user
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do
          member do
            get :index
            post :preferences_update
            get :account_create
            get :permissions_verified
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :terms
        get :privacy
        get :news
        get :trust_and_safety
        get :faq
        get :claim
        get :contact
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"

app/views/transactions/_details.haml
- if price_break_down_locals.present?
  .white-inner-box
    - if is_author
      .accept-button-box
        - if transaction_model.notification_status == 'sent'
          - if @current_user.stripe_details.present? && @current_user.is_verify
            = button_to t("transactions.accept"), notification_status_person_transaction_path(:id => params[:id], :person_id => params[:person_id], :notification_status => "accept" ), method: :post, :class => "notification_status transaction-accept button"
          - else
            = button_tag t("transactions.accept"), :class => "notification_status transaction-accept-wait", :type => "button"
          = button_to t("transactions.decline"), notification_status_person_transaction_path(:id => params[:id], :person_id => params[:person_id], :notification_status => "decline" ), method: :post, :class => "notification_status transaction-decline button"
        - elsif transaction_model.notification_status == 'accept'
          - if listing.author.strip_account_id.nil? && listing.author_id == @current_user.id
            = t("transactions.stripe_connect_owner")
          %button.waiting-button.custom-button{:type => "button"} WAITING FOR RENTER
        - elsif transaction_model.notification_status == 'paid'
          - renter = transaction_model.other_party(@current_user)
          - if price_break_down_locals[:end_on].past?
            - if transaction_model.author_skipped_feedback
              %h5
                You have skipped leaving a review. Reviews are important to the community.
                %br
                = link_to "Are you sure?", "/#{params[:locale]}/#{transaction_model.other_party(@current_user).username}/messages/#{transaction_model.id}/feedbacks/reopen", :method => :put
            - elsif transaction_model.testimonials.pluck(:author_id).exclude?(transaction_model.listing_author_id)
              - testimonial = Testimonial.new
              = render partial: "testimonials/testimonials_form", locals: { transaction: transaction_model, testimonial: testimonial }
            - else
              %h5
                You have left a review for
                = link_to renter.name(@current_community), person_path(renter)
          - else
            %p Get your gear ready! Booking is now complete. An email with information has been sent to you and the renter.
        - elsif transaction_model.notification_status == 'decline'
          %h5
            = link_to "You", person_path(listing.author)
            have declined this request.
      - if transaction_model.notification_status == 'sent'
        .payment-outer
          - unless @current_user.stripe_details.present?
            .payment-inner
              = image_tag("Paymentinfo_Icon.png")
              %p
                %strong You need
                to enter your
                %strong payment information
                in order to accept the booking
              = link_to "Enter payment information here", stripe_connect_person_settings_path(@current_user)
          - unless @current_user.is_verify
            .payment-inner
              = image_tag("ID-Icon.png")
              %p
                %strong
                  Upload ID
                to become a
                %strong verified user
                in order to accept the booking
              = link_to "Upload your ID right here",id_verification_person_settings_path(@current_user)
    - else
      - if transaction_model.notification_status == 'pending'
        .accept-button-box
          = button_to 'SEND BOOKING REQUEST', change_request_to_sent_person_transaction_path(@current_user, params[:id]), class: 'accept-button custom-button', method: :post
      - if transaction_model.notification_status == 'sent'
        .accept-button-box
          %button.waiting-button.custom-button{:type => "button"} WAITING FOR OWNER
      - if transaction_model.notification_status == 'accept'
        - if price_break_down_locals[:total_label].present?
          - price = price_break_down_locals[:subtotal]
        -else
          - price = price_break_down_locals[:listing_price]
        - if listing.renting_out_type?
          - convenience_fee = price_break_down_locals[:service_fee]
          - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price, :convenience_fee => convenience_fee)
        - else
          - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price)
        .accept-button-box
          = button_to 'ACCEPT AND COMPLETE', pay_url, class: 'accept-button custom-button', method: :post
      - if transaction_model.notification_status == 'paid'
        .accept-button-box
          - if price_break_down_locals[:end_on].past?
            - if transaction_model.starter_skipped_feedback
              %h5
                You have skipped leaving a review. Reviews are important to the community.
                %br
                = link_to "Are you sure?", "/#{params[:locale]}/#{transaction_model.other_party(@current_user).username}/messages/#{transaction_model.id}/feedbacks/reopen", :method => :put
            - elsif transaction_model.testimonials.pluck(:author_id).exclude?(transaction_model.starter_id)
              - testimonial = Testimonial.new
              = render partial: "testimonials/testimonials_form", locals: { transaction: transaction_model, testimonial: testimonial }
            - else
              - owner = transaction_model.other_party(@current_user)
              %h5
                You have left a review for
                = link_to owner.name(@current_community), person_path(owner)
          - else
            %p Booking is complete! An email with information has been sent to you and the owner. Have fun and be creative!
      - if transaction_model.notification_status == 'decline'
        .accept-button-box
          %h5
            = link_to listing.author.name(@current_community), person_path(listing.author)
            have declined this request.
    = render partial: "transactions/price_break_down", locals: price_break_down_locals
    = render :partial => 'transactions/renter_info', locals: { listing: listing, messages: messages, price_break_down_locals: price_break_down_locals, transaction_model: transaction_model }
- if @current_community.vat.present?
  .message-price-vat
    = t("conversations.show.price_excludes_vat")

  = render partial: "transactions/shipping_address", locals: { shipping_address: tx[:shipping_address] }

  %div{:id => "transaction_status"}
    = render :partial => "transactions/status/status", :locals => { :__transaction_model => transaction_model, role: role, is_author: is_author }

app/views/transactions/_notification_status.haml
- if is_author && transaction_model.notification_status == "pending"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "The renter has sent you a booking request"
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("request.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #3399ff;"}
                Request Received
            %span.initiate-transaction-per-unit-value.request-payment-2
              = button_tag t("transactions.accept"), :class => "notification_status accept_status transaction-accept", :value => "accept", :id => params[:id], :locale => params[:locale], :person_id => params[:person_id]
              = button_tag t("transactions.decline"), :class => "notification_status transaction-decline", :value => "decline", :id => params[:id], :locale => params[:locale], :person_id => params[:person_id]
              = image_tag "small_loader.gif", :class => "card_small_loader"
- if !is_author && transaction_model.notification_status == "pending"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Your request has been sent to the owner."
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label
              = image_tag("request.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #3399ff;"}
                Request Sent
- if is_author && transaction_model.notification_status == "accept"
  .message-avatar-padding
    .row
      .col-12
        - if listing.author.strip_account_id.nil? && listing.author_id == @current_user.id
          = t("transactions.stripe_connect_owner")
        %br
        %br
        %b
          Status:
        "Waiting for accept and payment from renter."
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("pending.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #cccc00;"}
                Pending
- elsif !is_author && transaction_model.notification_status == "accept"
  .message-avatar-padding
    .row
      .col-12
        - if @current_user.card_detail.nil?
          .initiate-transaction-totals
            - stripe_url = ( @current_user.card_detail.nil? || @current_user.card_detail.id.nil?) ? strip_credit_detail_person_settings_path(@current_user, :transaction => params[:id]) : strip_update_detail_person_settings_path(@current_user, :transaction => params[:id])
            The booking has been accepted. You need to enter your payment information
            = link_to "here", stripe_url
        - else
          - if listing.author.strip_account_id.nil? && listing.author_id != @current_user.id
            = t("transactions.stripe_connect")
          - elsif listing.author.strip_account_id.nil? && listing.author_id == @current_user.id
            = t("transactions.stripe_connect_owner")
          -else
            - if price_break_down_locals[:total_label].present?
              - price = price_break_down_locals[:total]
            -else
              - price = price_break_down_locals[:listing_price]
            - if  listing.renting_out_type?
              - convenience_fee = listing.convenience_fee(price_break_down_locals[:total], @current_community)
              - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price, :convenience_fee => convenience_fee)
            - else
              - pay_url = pay_stripe_amount_person_transaction_path(:person_id => @current_user.id, :id => params[:id], :price => price)
            %b
              Status:
            "Owner has accepted! Confirm upon agreement."
            .payment-status
              .initiate-transaction-per-unit-wrapper.notify
                %span.initiate-transaction-per-unit-label.request-payment-1
                  = image_tag("pending.png", :class => "payment-img")
                  %span{:class =>"payment-text", :style => "color: #cccc00;"}
                    Pending
                %span.initiate-transaction-per-unit-value
                  = button_to "CONFIRM", pay_url,:class => "stripe_pay_btn", :method => :post
- elsif is_author && transaction_model.notification_status == "paid"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Success! Make your gear ready for pickup. Have fun!"
        - if price_break_down_locals[:end_on].past?
          - if transaction_model.testimonials.pluck(:author_id).include?(transaction_model.listing_author_id) || transaction_model.author_skipped_feedback
            Already Reviewed.
          - else
            .status-links.row
              .inbox-horizontally-aligned-link.col-6
                %a.status-link{:href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/new"}
                  = image_tag("Leave_review_feedback.png")
              .inbox-horizontally-aligned-link.col-6
                %a.status-link.cancel{"data-method" => "put", "data-remote" => "true", :href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/skip"}
                  = image_tag("Skip_review.png")

        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("accepted.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #00cc66;"}
                Accepted
- elsif !is_author && transaction_model.notification_status == "paid"
  .message-avatar-padding
    .row
      .col-12
        %b
          Status:
        "Success. Have fun and be creative !"
        .payment-status
          .initiate-transaction-per-unit-wrapper.notify
            %span.initiate-transaction-per-unit-label.request-payment-1
              = image_tag("accepted.png", :class => "payment-img")
              %span{:class =>"payment-text", :style => "color: #00cc66;"}
                Accepted

        - if price_break_down_locals[:end_on].past?
          - if transaction_model.testimonials.pluck(:author_id).include?(transaction_model.starter_id) || transaction_model.starter_skipped_feedback
            Already Reviewed.
          - else
            .status-links.row
              .inbox-horizontally-aligned-link.col-6
                %a.status-link{:href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/new"}
                  = image_tag("Leave_review_feedback.png")
              .inbox-horizontally-aligned-link.col-6
                %a.status-link.cancel{"data-method" => "put", "data-remote" => "true", :href => "/#{params[:locale]}/#{transaction_model.payer.username}/messages/#{params[:id]}/feedbacks/skip"}
                  = image_tag("Skip_review.png")


:css
  .status-links{
    margin-top: 12px;
  }

app/views/transactions/_renter_info.haml
- renter = (listing.author == @current_user ? (messages.count > 0 && @current_user.id != messages.first[:sender][:id] ? Person.find(messages.first[:sender][:id]) : Person.find(messages.second[:sender][:id])) : @current_user)
.renter-info-box
  .renter-info-left
    .renter-info
      .renter-image
        = link_to image_tag(renter.image.url(:thumb), alt: ''), person_path(renter)
      = link_to person_path(renter) do
        %h6= renter.full_name
      .feedback-box
        - if renter.received_testimonials.size > 0
          - feedback = "#{renter.feedback_positive_percentage.to_s}% #{t("people.show.positive")} (#{renter.received_positive_testimonials.size}/#{renter.received_testimonials.size})"
        - else
          - feedback = 'No feedback yet'
        .feedback-icon
          %span.icon-star
        %p
          = feedback
          - unless feedback == 'No feedback yet'
            %br
            %span Feedback

app/views/transactions/_shipping_address.haml
- fields = [:name, :phone, :street1, :street2, :postal_code, :city, :state_or_province, :country]

- if shipping_address && shipping_address.slice(*fields).values.any?
  .shipping-address-container
    %h2= t("shipping_address.shipping_address")
    - fields.map do |field|
      - if shipping_address[field].present?
        - if shipping_address[field] == :name
          .shipping-address-name= shipping_address[field]
        - else
          .shipping-address-row= shipping_address[field]

app/views/transactions/new.haml
.process-box
  .owner-Info-box
    %h2.owner-Info-title
      = listing[:title]
    .owner-Info
      .owner-Info-image
        = link_to image_tag(listing.author.image.url(:thumb), alt: ''), person_path(listing.author)
      .owner-Info-content
        .owner-name
          = link_to person_path(listing.author) do
            %h6= author[:display_name]
        .feedback-box
          - if listing.author.received_testimonials.size > 0
            - feedback = "#{listing.author.feedback_positive_percentage.to_s}% #{t("people.show.positive")} (#{listing.author.received_positive_testimonials.size}/#{listing.author.received_testimonials.size})"
          - else
            - feedback = 'No feedback yet'
          .feedback-icon
            %span.icon-star
          %p
            = feedback
            - unless feedback == 'No feedback yet'
              %br
              %span Feedback
  .booking-status-bar
    .booking-status-col
      %label Request sent
      .booking-status-icon
        %img{:alt => "", :src => "/assets/icon1.png"}/
    .booking-status-col.center
      %label Owner accept
      .booking-status-icon
        %img{:alt => "", :src => "/assets/icon2.png"}/
    .booking-status-col
      %label You accept and complete
      .booking-status-icon
        %img{:alt => "", :src => "/assets/icon3.png"}/
  .info-text
    %p Write a message below before sending a booking request.
    %p You can always reach out to us, by using the livechat in the right hand corner.
  .booking-box
    - m_price_break_down.each do |price_break_down|
      .white-inner-box
        .accept-button-box
          %button.accept-button.custom-button{:type => "button"} SEND BOOKING REQUEST
        = render partial: "transactions/price_break_down", locals: price_break_down
        = render :partial => 'transactions/renter_info', locals: { listing: listing, messages: nil, price_break_down_locals: nil }
    = form_tag(form_action, method: :post, id: "transaction-form") do
      = hidden_field_tag(:start_on, booking_start)
      = hidden_field_tag(:end_on, booking_end)
      .chat-field
        = text_area_tag(:message, nil, :class => "text_area", :placeholder => "Write your messages here:", :required => true)
      - if quantity
        = hidden_field_tag(:quantity, quantity)
      .send-message-box
        = button_tag t("conversations.new.send_message"), :class => "send-button custom-button"
- content_for :extra_javascript do
  :javascript
    $('.accept-button').click(function() {
      var position = $("#transaction-form").offset().top
      $('html,body').animate({
        scrollTop: position
      }, 1000);
      $('.send-button').click();
    })

app/views/transactions/show.haml
- unless price_break_down_locals[:booking]
  #new_message_form.centered-section
    %h2= t("conversations.new.send_message_to_user", :person => listing.author.given_name_or_username)
.process-box-one
  .owner-Info-box
    - if price_break_down_locals[:booking]
      %h2.owner-Info-title
        = link_to_unless listing[:deleted], listing[:title], listing_path(id: listing[:id]), :class => "listing_title_head"
    .owner-Info
      .owner-Info-image
        = link_to image_tag(listing.author.image.url(:thumb), alt: ''), person_path(listing.author)
      .owner-Info-content
        .owner-name
          = link_to person_path(listing.author) do
            %h6= listing.author.full_name
        .feedback-box
          - if listing.author.received_testimonials.size > 0
            - feedback = "#{listing.author.feedback_positive_percentage.to_s}% #{t("people.show.positive")} (#{listing.author.received_positive_testimonials.size}/#{listing.author.received_testimonials.size})"
          - else
            - feedback = 'No feedback yet'
          .feedback-icon
            %span.icon-star
          %p
            = feedback
            - unless feedback == 'No feedback yet'
              %br
              %span Feedback
    - if price_break_down_locals[:booking]
      .booking-status-bar
        - class_name = ['sent', 'accept', 'paid'].include?(transaction_model.notification_status) ? 'active' : ''
        %div{class: "booking-status-col #{class_name}"}
          %label
            = is_author ? 'Request received' : 'Request sent'
          .booking-status-icon
            %img{:alt => "", :src => "/assets/icon1.png"}/
        - class_name = ['accept', 'paid'].include?(transaction_model.notification_status) ? 'active' : ''
        %div{class: "booking-status-col center #{class_name}"}
          %label
            = is_author ? 'You accept' : 'Owner accept'
          .booking-status-icon
            %img{:alt => "", :src => "/assets/icon2.png"}/
        - class_name = transaction_model.notification_status == 'paid' ? 'active' : ''
        %div{class: "booking-status-col #{class_name}"}
          %label
            = is_author ? 'Renter accepts' : 'You accept and complete'
          .booking-status-icon
            %img{:alt => "", :src => "/assets/icon3.png"}/

  - if !is_author && transaction_model.notification_status == 'pending' && price_break_down_locals[:booking]
    .info-text
      %p Write a message below before sending a booking request.
      %p You can always reach out to us, by using the livechat in the right hand corner.
  .booking-box
    - if price_break_down_locals[:booking]
      = render :partial => "transactions/details", locals: {role: role, tx: transaction, transaction_model: transaction_model, listing: listing, is_author: is_author, price_break_down_locals: price_break_down_locals, messages: messages}
    = render :partial => "conversations/messages_and_form", locals: {role: role, message_form: message_form, message_form_action: message_form_action, messages: messages}

.centered-section-wide.margin-from-top
  #messages
    = render :partial => "conversations/message", :collection => messages, as: :message_or_action